<a href="https://colab.research.google.com/github/paolanavarror/mineria-de-datos/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer Parcial

### Introducción

#### Conceptos

##### Minería de Datos:
Es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos.
##### Ciencia de datos:
Es el estudio de datos con el fin de extraer información significativa para empresas. Es un enfoque multidisciplinario que combina principios y prácticas del campo de las matemáticas, la estadística, la inteligencia artificial y la ingeniería de computación para analizar grandes cantidades de datos.

##### Comandos


Help and Documentation in IPython

In [1]:
help()

Welcome to Python 3.12's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
help(len)


Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
len?

In [ ]:
L = [1,2,3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):

SyntaxError: incomplete input (ipython-input-3003008882.py, line 1)

In [ ]:
square?

Object `square` not found.


In [ ]:
square??

Object `square` not found.


In [ ]:
len??

In [ ]:
L.<TAB>

SyntaxError: invalid syntax (ipython-input-3745167853.py, line 1)

In [ ]:
L.c<TAB>

SyntaxError: invalid syntax (ipython-input-379562613.py, line 1)

In [ ]:
L.cou<TAB>

SyntaxError: invalid syntax (ipython-input-2971403979.py, line 1)

In [ ]:
L._<TAB>

SyntaxError: invalid syntax (ipython-input-3055270103.py, line 1)

In [ ]:
from itertools import co<TAB>

SyntaxError: invalid syntax (ipython-input-461150734.py, line 1)

In [ ]:
import <TAB>

SyntaxError: invalid syntax (ipython-input-709411292.py, line 1)

In [ ]:
*Warning?

In [ ]:
str.*find*?

**IPython Magic Commands**

In [3]:
def donothing(x):
  return x

In [4]:
# El comando sirve para evaluar el desempeño en térmios de tiempo
%timeit L = [n ** 2 for n in range(1000)]

72.2 µs ± 697 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
# El comando %%timeit sirve para evaluar el desempeño solo que este abarca varias lineas de código en lugar de una
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

87.6 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
%timeit?

In [9]:
%%timeit?

**IPython and Shell Commands**

In [10]:
!ls

sample_data


In [12]:
%cd sample_data/

/content/sample_data


In [13]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [14]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [15]:
#Cuando tenermo svariables de ambiente podemso mofiicar variables y cambiar el comportomaiento
# Sirve para ver las variables de entorno
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'b506c8c217e8',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

**Understanding Data Types in Python**

c es un lenguaje altamente tipado, una vez que declaramos una variable se queda con el mismo tipo.
Pyhton es un lenguaje de tipado dinamico.





Una estructura dentro de esa estructutara esst el tipo, el tamaño, etc
Tipo de objeto: modifica el tipo del variable que estamos utilizando
Una lisa en Py es una secuencia de, podemos tener

In [16]:
  #Cusndo importamos un paquet en Py utilizamos np
  import numpy as np

In [18]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [19]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [20]:
#Es un tipo de float, de que tan preciso
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Listas de contencipon, arreglos bideminionales, cliclos anidados
#Ejecuta este de ranfo tmoando el primero de la lista, en Py un rango genera una secuencia, con el
# Empieza en 2 y termina antes del 5
#Luego toma el rango del 6 y lo
np.array([range(i, i + 3) for i in [2, 4, 6]])