<a href="https://colab.research.google.com/github/paolanavarror/mineria-de-datos/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer Parcial

### Introducción

#### Conceptos

##### Minería de Datos:
Es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos.
##### Ciencia de datos:
Es el estudio de datos con el fin de extraer información significativa para empresas. Es un enfoque multidisciplinario que combina principios y prácticas del campo de las matemáticas, la estadística, la inteligencia artificial y la ingeniería de computación para analizar grandes cantidades de datos.

##### Comandos


Help and Documentation in IPython

In [ ]:
help()

Welcome to Python 3.12's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.12/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q" or "quit".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
help(len)


Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1,2,3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):

SyntaxError: incomplete input (ipython-input-3003008882.py, line 1)

In [ ]:
square?

Object `square` not found.


In [ ]:
square??

Object `square` not found.


In [ ]:
len??

In [ ]:
L.<TAB>

SyntaxError: invalid syntax (ipython-input-3745167853.py, line 1)

In [ ]:
L.c<TAB>

SyntaxError: invalid syntax (ipython-input-379562613.py, line 1)

In [ ]:
L.cou<TAB>

SyntaxError: invalid syntax (ipython-input-2971403979.py, line 1)

In [ ]:
L._<TAB>

SyntaxError: invalid syntax (ipython-input-3055270103.py, line 1)

In [ ]:
from itertools import co<TAB>

SyntaxError: invalid syntax (ipython-input-461150734.py, line 1)

In [ ]:
import <TAB>

SyntaxError: invalid syntax (ipython-input-709411292.py, line 1)

In [ ]:
*Warning?

In [ ]:
str.*find*?

**IPython Magic Commands**

In [ ]:
def donothing(x):
  return x

In [ ]:
# El comando sirve para evaluar el desempeño en térmios de tiempo
%timeit L = [n ** 2 for n in range(1000)]

72.2 µs ± 697 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando %%timeit sirve para evaluar el desempeño solo que este abarca varias lineas de código en lugar de una
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

87.6 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

**IPython and Shell Commands**

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
#Cuando tenermo svariables de ambiente podemso mofiicar variables y cambiar el comportomaiento
# Sirve para ver las variables de entorno
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'b506c8c217e8',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

**Understanding Data Types in Python**

c es un lenguaje altamente tipado, una vez que declaramos una variable se queda con el mismo tipo.
Pyhton es un lenguaje de tipado dinamico.





Una estructura dentro de esa estructutara esst el tipo, el tamaño, etc
Tipo de objeto: modifica el tipo del variable que estamos utilizando
Una lisa en Py es una secuencia de, podemos tener

In [ ]:
  #Cusndo importamos un paquet en Py utilizamos np
  import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#Es un tipo de float, de que tan preciso
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Listas de contencipon, arreglos bideminionales, cliclos anidados
#Ejecuta este de ranfo tmoando el primero de la lista, en Py un rango genera una secuencia, con el
# Empieza en 2 y termina antes del 5
#Luego toma el rango del 6 y lo
np.array([range(i, i + 3) for i in [2, 4, 6]])

Semana 2 (26-28 de Enero del 2026)

**The Basics of NumPy Arrays**

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)  # seed for reproducibility


In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array Genera un arreglo aletorio de enteros del 0 al 10 de tamaño 6
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array, 3 renglones 4 columnas
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array,

In [ ]:
print("x3 ndim: ", x3.ndim) #La propiedad ndim nos dice el num de dimensiones, con la propiedad ndim, n: numero dim: dimension
print("x3 shape:", x3.shape) #3 renglones, 4 columnas, 5 planos de ese tipo
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print(x2.dtype) #Nos dice el tipo de datos

int64


In [ ]:
print("dtype:", x3.dtype) #los 64 bits estan agrupados en 8 bytes

dtype: int64


In [ ]:
#No es lo mismo almacenar entero que flotantes, se coupa mas memoria en flotantes
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes") #nbytes

itemsize: 8 bytes
nbytes: 480 bytes


**Array Indexing: Accessing Single**



In [ ]:
x1

array([4, 3, 4, 4, 8, 4])

In [ ]:
x1[0] #Colocamos el indice del elemento a extraer, en este caso el primer elemento tiene el indice 0

np.int64(4)

In [ ]:
x1[4]

np.int64(8)

In [ ]:
#Para ondexar de la forma desdes de la parte de atras se coloca el sogno -
x1[-1] #Nos regresa el ultimo elemento del ndarray

np.int64(4)

In [ ]:
x2 #Nos trae digitos del 0-9 nos trae 4 columnas

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [ ]:
x2[0,0]

np.int64(3)

In [ ]:
x2[0,2]

np.int64(5)

In [ ]:
#desde atras renglon
x2[2, -1]

np.int64(0)

In [ ]:
x2[0,0] = 12 #Asignar un nuevo valor (12) al renlglón 0 columna 0
x2 #se coloca el arreglo para que lo muestre

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

#### Estadistica Básica

https://github.com/jesusrevilla/mineria-de-datos/blob/main/primer-parcial/00_analisis_estadistico_numpy.md

ndarray: es n dimension

Media (Mean)

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)
#se observa que regresa un num flotante

3.0


Promedio (Average) y Promedio Ponderado

In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [ ]:
#Lo que hace diferente a promedio a un promedio ponderado a cada elemento le pudede dar un peso diferente
#Promedio ponderado: Para darle un peso distinto a cada uno de los elementos
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [ ]:
mediana = np.median(data)

La mediana, la media, promedio, nos decriben en su parte central
Uno de tendencia central y uno de dispersión, el de dispersión no

Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data) #var: varianza
desviacion = np.std(data) #std: estandar

Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000) #genera num que siguen la distribucipón de gauss
print(np.mean(muestra), np.std(muestra)) # #Para poder decribir un conjunto de datos

-0.06822848283196342 0.9888713702612747


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7]) #entre mas se acerque a 1 mas fuerte es la corelación
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

In [ ]:
# Manejo de NaN (np.nanmean, etc.), maneja

Semana 2 (Martes 27 de Enero)

Cuadros estadisticos

In [1]:

import numpy as np
import pandas as pd
from io import StringIO #metodo para convertir cadena de caracterers en

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t') #strinOI permite convertir texto como si fuera archivo separado por tab
df.columns = [c.strip() for c in df.columns] #aplica  una lista por, strip sirve para eliminar espacios

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce') #metodo de pandas que df: dataframe realiza, cuando lo llamamos
map_sn = {'Si': True, 'No': False} #aqui apenas es el mapeo
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn) #esta columna va a tener valores booleanos
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)



In [2]:
df.head() #Me trae los primeros 5 datos

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [3]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float) #
prog_py = df['prog_python'].to_numpy(dtype=bool) #tomamos la columna que ya se convirtió a bool y lo convierte a numpy y ahí van datos bool
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [5]:
edad[:5] #me trae los primeros 5 elementos del arreglo

array([22., 21., 26., 21., 24.])

In [6]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size), #edad es un arreglo del numpy, cuantos elemnetos tiene el arreglo de edad
    'min': float(np.min(edad)), #va a traer la edad menor
    'p25': float(np.percentile(edad, 25)), #Va a traer el 25% de los datos
    'mediana': float(np.median(edad)), #medida de tendencia central, se ordenan los datos de menor a maypr y se obtiene
    'media': float(np.mean(edad)), #promedio
    'p75': float(np.percentile(edad, 75)), #el 75% de los datos que
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)), #variancia
    'std_muestral': float(np.std(edad, ddof=1)), #std: desviación estandar
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)), #cv: coeficiente de variancia
}

In [7]:
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [8]:
#media: la media es insensible a esas
#p75: cant de datos desde

In [9]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))} #diccionario de las frecuencias de los que han usado python, se estan contanto los que no son 0
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))} #
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [11]:
print (f'Frecuencia de utilización de Python: {freq_python}') #f: para decir qwu es un fstring y lo que este fuera d {}
print (f'Frecuencia de utilización de Colab: {freq_colab}')
print (f'Frecuencia de utilización de GitHub: {freq_gh}')

Frecuencia de utilización de Python: {'Si': 54, 'No': 6}
Frecuencia de utilización de Colab: {'Si': 18, 'No': 42}
Frecuencia de utilización de GitHub: {'Si': 52, 'No': 8}


In [15]:
# Tablas cruzadas (NumPy)
#definifición de funcipon
def tabla2x2(a, b): #palabra reservada def es para definir una función
    t = np.zeros((2,2), dtype=int) #np.zeros genera un arreglo, una matriz de 2 renglones y de 2 columnas rellenas de 0 de tipo entero
    t[1,1] = np.count_nonzero(a & b) #asigna valores utilizando coordenadas, es decir en la, esta haciendo una op and
    t[1,0] = np.count_nonzero(a & ~b) # not, se eta haciesnd una op and pero se esta negando  el parametro a
    t[0,1] = np.count_nonzero(~a & b) #
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [17]:
print (f'Tabla 2x2 de Python y Colab \n {tab_py_colab}') #El  18 es la combinacipon de que sabe usar python y colab

Tabla 2x2 de Python y Colab 
 [[ 6  0]
 [36 18]]


In [19]:
print (f'Tabla 2x2 de Python y GitHub \n {tab_py_gh}') #47 saben usar py y  gh y 1 es que no sabe usar ninguno de los 2, 5 no sabe usar py pero si gh

Tabla 2x2 de Python y GitHub 
 [[ 1  5]
 [ 7 47]]


In [18]:
# Medias de edad por grupo (NumPy)
#Genera todas las
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})

Conclusión : Con la libreria Numpy se le puede hacer operaciones vectoriales
copiar toda la cadena sustiruir por , todo lo que tenga por
copiar el texto, colocarlo en un bloc de notas reopkazar los /t por , y los subimos por

In [21]:
#Cargar datos
df = pd.read_csv(StringIO(raw), sep=',')
df.columns = [c.strip() for c in df.columns]